baseUrl = https://qa-automation-practice.netlify.app/ 
browser = chrome
username =
password =


//Yha wo data add hoga jo generic h like jo har test case mein use hoga. Iska benefit yeh h ki humme bina iss file k
//har bar jab bhi test execute honge toh manaully url ya browser dena hoga aur suppose agar url change hua toh har 
//jagah se change karna hoga
//cross browser testing k liye yha browser ki value change kardo do aur ya parameters concept use karke testng.xml mein use karo